name = "DotCall"
uuid = "c8efb2cb-5e3b-4fe2-bcce-5cd9f862e77b"
authors = ["John Lapeyre <jlapeyre@users.noreply.github.com> and contributors"]
version = "0.2.0"

[compat]
Aqua = ">= 0.8"
julia = "1.7"
JET = ">= 0.0"
Test = ">= 0.0"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Aqua", "JET"]
