name = "DotCall"
uuid = "c8efb2cb-5e3b-4fe2-bcce-5cd9f862e77b"
authors = ["John Lapeyre <jlapeyre@users.noreply.github.com> and contributors"]
version = "0.2.0"

[compat]
julia = "1.7"
Test = ">= 0.0"
Aqua = ">= 0.8"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Aqua"]
